# Generated by Django 4.1.2 on 2022-11-10 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_code', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('announcement', models.TextField(null=True)),
                ('seller_specifics', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_code', models.IntegerField()),
                ('product_name', models.CharField(max_length=200)),
                ('product_state', models.CharField(max_length=10)),
                ('product_price', models.IntegerField()),
                ('vat', models.CharField(max_length=10)),
                ('stock_num', models.IntegerField()),
                ('main_img', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=50)),
                ('manufacturer', models.CharField(max_length=50)),
                ('manufacturing_date', models.DateField(null=True)),
                ('effective_date', models.DateField(null=True)),
                ('origin_code', models.CharField(max_length=10)),
                ('importer', models.CharField(max_length=50)),
                ('is_plural_origin', models.BooleanField()),
                ('origin_direct_input', models.CharField(max_length=50, null=True)),
                ('info_template_code', models.IntegerField(null=True)),
                ('info_name', models.CharField(max_length=100, null=True)),
                ('info_model_name', models.CharField(max_length=100, null=True)),
                ('info_authorization', models.TextField(null=True)),
                ('info_manufacturer', models.TextField(null=True)),
                ('pc_instant_discount_value', models.IntegerField(null=True)),
                ('pc_instant_discount_unit', models.CharField(max_length=10, null=True)),
                ('mobile_instant_discount_value', models.IntegerField(null=True)),
                ('mobile_instant_discount_unit', models.CharField(max_length=10, null=True)),
                ('multiple_purchase_discount_condition_value', models.IntegerField(null=True)),
                ('multiple_purchase_discount_condition_unit', models.CharField(max_length=10, null=True)),
                ('multiple_purchase_discount_value', models.IntegerField(null=True)),
                ('multiple_purchase_discount_unit', models.CharField(max_length=10, null=True)),
                ('interset_free_installment_month', models.IntegerField(null=True)),
                ('gift', models.CharField(max_length=100, null=True)),
                ('review_exposure_state', models.BooleanField(null=True)),
                ('review_non_exposure_reson', models.TextField(null=True)),
                ('after_service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naver.as')),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_template_code', models.IntegerField(null=True)),
                ('type', models.CharField(choices=[('택배, 소포, 등기', 'delivery'), ('직접배송(화물배달)', 'direct_delivery')], max_length=30, null=True)),
                ('courier_code', models.IntegerField(null=True)),
                ('cost_type', models.CharField(choices=[('무료', 'free'), ('조건부 무료', 'conditionally_free'), ('유료', 'charged'), ('수량별', 'by_quantity'), ('구간별', 'by_section')], max_length=10, null=True)),
                ('default_cost', models.IntegerField(null=True)),
                ('cost_payment_type', models.CharField(choices=[('착불', 'pay_on_delivery'), ('선결제', 'prepayment'), ('착불 또는 선결제', 'all')], max_length=10, null=True)),
                ('return_cost', models.IntegerField(null=True)),
                ('exchange_cost', models.IntegerField(null=True)),
                ('extra_installation_cost', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubImg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naver.shipping'),
        ),
        migrations.CreateModel(
            name='OptionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_type', models.CharField(max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product')),
            ],
        ),
        migrations.CreateModel(
            name='OptionStockNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.option')),
            ],
        ),
        migrations.CreateModel(
            name='OptionName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='option_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.optionname'),
        ),
        migrations.CreateModel(
            name='DirectInputOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.IntegerField(null=True)),
                ('ISSN', models.IntegerField(null=True)),
                ('is_independent_publication', models.BooleanField(null=True)),
                ('publication_date', models.DateField(null=True)),
                ('publisher', models.CharField(max_length=100, null=True)),
                ('writer', models.CharField(max_length=100, null=True)),
                ('painter', models.CharField(max_length=100, null=True)),
                ('translator', models.CharField(max_length=100, null=True)),
                ('is_cultural_expenses_income_tax_deduction', models.BooleanField(null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProductName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('num', models.IntegerField()),
                ('additional_product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.additionalproductname')),
            ],
        ),
    ]
