# Generated by Django 4.1.2 on 2022-11-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_plural_origin',
            field=models.BooleanField(null=True),
        ),
    ]
