# Generated by Django 4.1.2 on 2022-11-10 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0002_alter_product_is_plural_origin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AS',
            new_name='AfterService',
        ),
        migrations.AddField(
            model_name='product',
            name='option_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='OptionType',
        ),
    ]
