# Generated by Django 4.1.2 on 2022-11-17 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0003_rename_as_afterservice_product_option_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='after_service',
        ),
        migrations.AddField(
            model_name='afterservice',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='naver.product'),
        ),
    ]
