# Generated by Django 4.1.2 on 2022-11-17 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0004_remove_product_after_service_afterservice_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product'),
        ),
    ]
