# Generated by Django 4.1.2 on 2022-11-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0006_fileupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
