# Generated by Django 4.1.2 on 2022-11-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0007_alter_fileupload_imgfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='product',
        ),
    ]
