# Generated by Django 4.1.2 on 2022-11-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0008_remove_fileupload_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileUpload',
        ),
    ]
