# Generated by Django 4.1.2 on 2022-11-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0009_delete_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
