# Generated by Django 4.1.2 on 2022-11-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0010_shipping_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipping',
            name='title',
        ),
        migrations.AddField(
            model_name='shipping',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
