# Generated by Django 4.1.2 on 2022-11-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0011_remove_shipping_title_shipping_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='cost_payment_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='cost_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='type',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
