# Generated by Django 4.1.2 on 2022-11-25 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0012_alter_shipping_cost_payment_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipping',
            old_name='name',
            new_name='title',
        ),
    ]
