# Generated by Django 4.1.2 on 2022-11-26 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0014_alter_shipping_courier_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='afterservice',
            name='announcement',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='afterservice',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='afterservice',
            name='seller_specifics',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_cultural_expenses_income_tax_deduction',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_independent_publication',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='painter',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='gift',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='info_authorization',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='info_manufacturer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='info_model_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='info_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='interset_free_installment_month',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_plural_origin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='mobile_instant_discount_unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='mobile_instant_discount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiple_purchase_discount_condition_unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiple_purchase_discount_condition_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiple_purchase_discount_unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='multiple_purchase_discount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='option_type',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_direct_input',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='pc_instant_discount_unit',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='pc_instant_discount_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_exposure_state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='review_non_exposure_reson',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='vat',
            field=models.CharField(default='과세상품', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='cost_payment_type',
            field=models.CharField(default='선결제', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='cost_type',
            field=models.CharField(default='무료', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='type',
            field=models.CharField(default='', max_length=30),
        ),
    ]
