# Generated by Django 4.1.2 on 2022-12-05 08:26

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0015_alter_afterservice_announcement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail_descript',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
