# Generated by Django 4.1.2 on 2022-12-05 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0016_remove_product_info_template_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(verbose_name='판매가'),
        ),
    ]
