# Generated by Django 4.1.2 on 2022-12-06 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0016_product_detail_descript'),
        ('naver', '0016_remove_product_info_template_code_and_more'),
    ]

    operations = [
    ]
