# Generated by Django 4.1.2 on 2022-12-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0016_product_detail_descript'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='detail_descript',
            new_name='detail_description',
        ),
    ]
