# Generated by Django 4.1.2 on 2022-12-06 06:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0017_alter_product_name_alter_product_price'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='afterservice',
        #     name='template_code',
        # ),
        migrations.AlterField(
            model_name='additionalproductdetail',
            name='additional_product_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.additionalproductname', verbose_name='추가상품명'),
        ),
        migrations.AlterField(
            model_name='additionalproductdetail',
            name='num',
            field=models.IntegerField(verbose_name='재고수량'),
        ),
        migrations.AlterField(
            model_name='additionalproductdetail',
            name='price',
            field=models.IntegerField(verbose_name='상품가'),
        ),
        migrations.AlterField(
            model_name='additionalproductdetail',
            name='value',
            field=models.CharField(max_length=50, verbose_name='추가상품값'),
        ),
        migrations.AlterField(
            model_name='additionalproductname',
            name='name',
            field=models.CharField(max_length=50, verbose_name='추가상품명'),
        ),
        migrations.AlterField(
            model_name='additionalproductname',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='afterservice',
            name='announcement',
            field=models.TextField(verbose_name='A/S 안내사항'),
        ),
        migrations.AlterField(
            model_name='afterservice',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='A/S 전화번호'),
        ),
        migrations.AlterField(
            model_name='afterservice',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product', verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='afterservice',
            name='seller_specifics',
            field=models.TextField(default='', verbose_name='판매자특이사항'),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISSN',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_cultural_expenses_income_tax_deduction',
            field=models.BooleanField(default=False, verbose_name='문화비 소득공제'),
        ),
        migrations.AlterField(
            model_name='book',
            name='is_independent_publication',
            field=models.BooleanField(blank=True, default=False, verbose_name='독립출판'),
        ),
        migrations.AlterField(
            model_name='book',
            name='painter',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='그림작가'),
        ),
        migrations.AlterField(
            model_name='book',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product', verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publication_date',
            field=models.DateField(blank=True, null=True, verbose_name='출간일'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='출판사'),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='번역자명'),
        ),
        migrations.AlterField(
            model_name='book',
            name='writer',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='글작가'),
        ),
        migrations.AlterField(
            model_name='directinputoption',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='directinputoption',
            name='text',
            field=models.CharField(max_length=50, verbose_name='옵션명'),
        ),
        migrations.AlterField(
            model_name='option',
            name='option_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.optionname', verbose_name='옵션'),
        ),
        migrations.AlterField(
            model_name='option',
            name='price',
            field=models.IntegerField(verbose_name='옵션가'),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(max_length=50, verbose_name='옵션값'),
        ),
        migrations.AlterField(
            model_name='optionname',
            name='name',
            field=models.CharField(max_length=50, verbose_name='옵션명'),
        ),
        migrations.AlterField(
            model_name='optionname',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_name', to='naver.product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='optionstocknum',
            name='num',
            field=models.IntegerField(verbose_name='재고수량'),
        ),
        migrations.AlterField(
            model_name='optionstocknum',
            name='option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.option', verbose_name='옵션'),
        ),
        migrations.AlterField(
            model_name='subimg',
            name='img',
            field=models.ImageField(upload_to=''),
        ),
    ]
