# Generated by Django 4.1.2 on 2022-12-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0018_remove_afterservice_template_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ISBN',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='ISSN',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
