# Generated by Django 4.1.2 on 2022-12-21 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0018_rename_detail_descript_product_detail_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='naver.product', verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='optionstocknum',
            name='option',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='naver.option', verbose_name='옵션'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=50, verbose_name='브랜드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='effective_date',
            field=models.DateField(blank=True, null=True, verbose_name='유효일자'),
        ),
        migrations.AlterField(
            model_name='product',
            name='importer',
            field=models.CharField(blank=True, max_length=50, verbose_name='수입사'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_plural_origin',
            field=models.BooleanField(default=False, verbose_name='복수원산지여부'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(max_length=300, upload_to='', verbose_name='대표이미지'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='제조사'),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturing_date',
            field=models.DateField(blank=True, null=True, verbose_name='제조일자'),
        ),
        migrations.AlterField(
            model_name='product',
            name='option_type',
            field=models.CharField(blank=True, choices=[('', ''), ('단독형', '단독형'), ('조합형', '조합형')], default='', max_length=10, verbose_name='옵션형태'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_code',
            field=models.CharField(max_length=10, verbose_name='원산지코드'),
        ),
        migrations.AlterField(
            model_name='product',
            name='origin_direct_input',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='원산지 직접입력'),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='title',
            field=models.CharField(max_length=200, verbose_name='제목'),
        ),
        migrations.AlterField(
            model_name='subimg',
            name='img',
            field=models.ImageField(max_length=300, upload_to=''),
        ),
    ]
