# Generated by Django 4.1.2 on 2022-12-29 06:37

from django.db import migrations, models
import naver.common


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0019_alter_book_product_alter_optionstocknum_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='url',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_img',
            field=models.ImageField(max_length=300, upload_to=naver.common.image_upload_path, verbose_name='대표이미지'),
        ),
        migrations.AlterField(
            model_name='subimg',
            name='img',
            field=models.ImageField(max_length=300, upload_to=naver.common.image_upload_path),
        ),
    ]
