# Generated by Django 4.1.2 on 2022-12-06 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0019_alter_book_isbn_alter_book_issn'),
    ]

    operations = [
        migrations.AddField(
            model_name='afterservice',
            name='template_code',
            field=models.IntegerField(null=True),
        ),
    ]
