# Generated by Django 4.1.2 on 2022-12-06 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0020_afterservice_template_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optionname',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naver.product', verbose_name='상품'),
        ),
        migrations.AlterField(
            model_name='subimg',
            name='img',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
