# Generated by Django 4.1.2 on 2022-12-29 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naver', '0020_product_url_alter_product_main_img_alter_subimg_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.CharField(max_length=400),
        ),
    ]
